# Generated by Django 5.2.10 on 2026-02-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_share_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reels/'),
        ),
    ]
