# Generated by Django 5.2.10 on 2026-02-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_is_read_message_shared_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='shared_post',
            new_name='post',
        ),
    ]
