# Generated by Django 5.2.10 on 2026-02-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_read_message_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
